const express = require('express');
const { shareData } = require('../controllers/data');

const router = express.Router();

router
  .route('/:id/:requestType')
  .get(shareData) // share a file by an id generated by a UUID

module.exports = router;